# Generated by Django 2.1.5 on 2019-01-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_train',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='label',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
