# Generated by Django 2.1.5 on 2019-01-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews_api', '0002_auto_20190119_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='label',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
