# Generated by Django 2.1.5 on 2019-01-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews_api', '0004_auto_20190119_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.TextField(),
        ),
    ]
