# Generated by Django 2.1.5 on 2019-01-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews_api', '0005_auto_20190119_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
