# Generated by Django 2.1.5 on 2019-01-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews_api', '0006_auto_20190119_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
