# Generated by Django 2.1.5 on 2019-01-31 19:03

from django.db import migrations
import djongo.models.fields
import intapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportEntry',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('report', djongo.models.fields.EmbeddedModelField(model_container=intapp.models.Report, null=True)),
            ],
        ),
    ]
